language: python

cache: 
  - pip
  - directories:
    - 'tests/vcr'

python:
  - '3.5'

install:
  - pip install -r requirements.txt
  - pip install --upgrade codecov
  - pip install --upgrade pytest-cov
  - pip install --upgrade vcrpy
  - pip install --upgrade -e .

notifications:
  email: false

script:
  - py.test --cov unsplash_python --cov-report term-missing --cov-report xml

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

branches:
  only:
    - master

deploy:
  provider: pypi
  user: superbox
  password:
    secure: VP5pGz7t3I4SmLclBwJdUmXdx6ulT4DzW9VMb1DHeX3xA9n95mg62ipKPad6h4o+I7/CUKN/djiq75mOEqLt4N2bMSJwlSEeGbbzP/26c963v8xaJRaUqk2EMmCSxMQyvGDY7ggOrosK9wpKepkPZO+6lpckFv8tVdXgpwqsH4Or5qVZkSyprIqszAT1jz9Bwfk+4CDbSHANdMD225ejJxJiY7hFbGjx11+3FBQwN5UdsiWySHE9IeGYXVLtA3Lke1Ff78LZ/AdQ8cROFadN8HNNaxCCrOVnxcR1IdG/64ObSsso2AeivOwgwaWtE3MRFkHoIpR9fHxDMXCmcdZL5y3Z9o6X9f1EK2CEx4s0A4Eq7u8TsPGNib1cFANDPrQEhb17PXNelJ8hHfwx5LJcEGfMMuKtIw20Q5B8qAIKmSBTLLfDTCktm9Ts0j7Y0pwn+8ShXIbMfhiEn3eeCfVn2FPbLgnUYCCN3+yjmD5g+XHOL5Llx9joWBHfcoBmG8kFjDnlo6oJlmcLVgL1RnA15FSmy6E1s+sGDdhUiyTp4GuKd9dY8KvG0pIjoZ0in7TrzbP+klwhj4YTgthy/SthjRWv9J2Qh6x7DYR8JDPEGqNNUpCYxbON5eMi34gpGd7WvTaDycbgopb1ofB8/K7u5hLwG4SPB8sfO+5cOUPk7fE=
  distributions: 'bdist_wheel'
  on:
    tags: true
    branch: master
