language: python

cache: 
  - pip
  - directories:
    - 'tests/vcr'

python:
  - '3.5'

install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest-pep8
  - pip install --upgrade vcrpy
  - pip install --upgrade -e .

notifications:
  email: false

script:
  - py.test --pep8
  - py.test